android_binary(
    name = 'myapp',
    legacy_native_support = 0,
    manifest = 'AndroidManifest.xml',
    deps = ['//project:main'],

    resource_files = glob(['res/**']),

    assets = glob(['assets/**']),
    assets_dir = 'assets'
)
